codecov:
  token: "6040de41-c073-4d6f-bbf8-d89256ef31e1"
  disable_default_path_fixes: true

fixes:
  - "github.com/lfch/etcd-io/api/v3/::api/"
  - "github.com/lfch/etcd-io/client/v3/::client/v3/"
  - "github.com/lfch/etcd-io/client/v2/::client/v2/"
  - "github.com/lfch/etcd-io/etcdctl/v3/::etcdctl/"
  - "github.com/lfch/etcd-io/pkg/v3/::pkg/"
  - "github.com/lfch/etcd-io/raft/v3/::raft/"
  - "github.com/lfch/etcd-io/server/v3/::server/"

ignore:
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "tests/**/*"
  - "github.com/lfch/etcd-io/tests/**/*"
